import type { Product } from "@/types/product";

export const products: Product[] = [
  {
    id: "1",
    slug: "luna-kolye",
    name: "Luna Kolye",
    description: "Ayın en parlak halinden ilham alan Luna, minimalist çizgileriyle günlük zarafetinizi tamamlar.",
    story: "Her gece gökyüzünde parlayan ay, Luna koleksiyonumuzun ilham kaynağıdır. Ustalarımız tarafından tek tek elle cilalanır ve her parça benzersiz bir ışıltı taşır.",
    price: 1250,
    category: "necklaces",
    materials: ["925 Ayar Gümüş", "18K Altın Kaplama"],
    sustainability: "Geri dönüştürülmüş gümüş kullanılarak üretilmiştir.",
    images: ["/products/luna-1.jpg", "/products/luna-2.jpg"],
    inStock: true,
    featured: true,
  },
  {
    id: "2",
    slug: "aurora-yuzuk",
    name: "Aurora Yüzük",
    description: "Kuzey ışıklarının büyüleyici dansından ilham alan Aurora, zarif ve cesur bir parça.",
    story: "Kuzey ışıklarının gökyüzünde yarattığı o büyülü anı yakalamak istedik. Aurora, ışığın metallerle buluştuğu minimalist bir başyapıttır.",
    price: 890,
    category: "rings",
    materials: ["925 Ayar Gümüş"],
    sustainability: "Etik kaynaklardan temin edilmiş malzemelerle üretilmiştir.",
    images: ["/products/aurora-1.jpg", "/products/aurora-2.jpg"],
    inStock: true,
    featured: true,
  },
  {
    id: "3",
    slug: "stella-kupe",
    name: "Stella Küpe",
    description: "Yıldızların ışıltısını taşıyan Stella, her anınıza zarif bir parlaklık katar.",
    story: "Gece gökyüzündeki yıldızların sonsuz zarafetinden doğan Stella, kulağınızda hafif ve şık bir dokunuş bırakır.",
    price: 680,
    category: "earrings",
    materials: ["925 Ayar Gümüş", "Zirkon Taş"],
    sustainability: "Çevre dostu ambalaj ile teslim edilir.",
    images: ["/products/stella-1.jpg", "/products/stella-2.jpg"],
    inStock: true,
    featured: true,
  },
  {
    id: "4",
    slug: "ivy-bileklik",
    name: "Ivy Bileklik",
    description: "Doğanın zarif kıvrımlarından ilham alan Ivy, bileğinizi sarmalayan ince bir dokunuş.",
    story: "Sarmaşıkların doğada yarattığı organik çizgiler, Ivy bilekliğimizin tasarım felsefesini oluşturur. Doğallık ve zarafet bir arada.",
    price: 750,
    category: "bracelets",
    materials: ["925 Ayar Gümüş", "18K Altın Kaplama"],
    sustainability: "Sürdürülebilir üretim süreçleriyle imal edilmiştir.",
    images: ["/products/ivy-1.jpg", "/products/ivy-2.jpg"],
    inStock: true,
    featured: true,
  },
  {
    id: "5",
    slug: "nova-kolye",
    name: "Nova Kolye",
    description: "Bir yıldızın doğuşunu simgeleyen Nova, göğsünüzde parlayan zarif bir ışık.",
    story: "Evrenin derinliklerinde doğan yeni yıldızlar gibi, Nova kolye de her giyildiğinde yeni bir ışıltı sunar.",
    price: 1450,
    category: "necklaces",
    materials: ["925 Ayar Gümüş", "14K Altın"],
    sustainability: "Karbon nötr üretim süreciyle üretilmiştir.",
    images: ["/products/nova-1.jpg", "/products/nova-2.jpg"],
    inStock: true,
    featured: false,
  },
  {
    id: "6",
    slug: "eden-yuzuk",
    name: "Eden Yüzük",
    description: "Cennet bahçesinin sadeliğinden ilham alan Eden, parmağınızda huzur veren bir parça.",
    story: "Eden, karmaşanın ortasında sadeliğin gücünü hatırlatır. Temiz çizgileri ve minimal formuyla günlük şıklığınızın vazgeçilmezi.",
    price: 720,
    category: "rings",
    materials: ["925 Ayar Gümüş"],
    sustainability: "Geri dönüştürülmüş malzemelerle üretilmiştir.",
    images: ["/products/eden-1.jpg", "/products/eden-2.jpg"],
    inStock: true,
    featured: false,
  },
  {
    id: "7",
    slug: "pearl-kupe",
    name: "Pearl Küpe",
    description: "Denizin derinliklerinden gelen zarafet. Pearl, klasik inci estetiğini modern çizgilerle buluşturur.",
    story: "İncinin doğadaki yolculuğu, sabır ve zarafetin sembolüdür. Pearl küpelerimiz bu yolculuğun minimalist bir yansımasıdır.",
    price: 920,
    category: "earrings",
    materials: ["925 Ayar Gümüş", "Tatlı Su İncisi"],
    sustainability: "Sorumlu kaynaklardan temin edilmiş inciler kullanılmıştır.",
    images: ["/products/pearl-1.jpg", "/products/pearl-2.jpg"],
    inStock: true,
    featured: false,
  },
  {
    id: "8",
    slug: "aura-bileklik",
    name: "Aura Bileklik",
    description: "Enerjinizi yansıtan Aura, bileğinizde ince ve zarif bir halka oluşturur.",
    story: "Her insanın kendine özgü bir aurası vardır. Bu bileklik, o görünmez enerjiyi gümüşün zarif çizgileriyle görünür kılar.",
    price: 580,
    category: "bracelets",
    materials: ["925 Ayar Gümüş"],
    sustainability: "Minimal ambalaj ve çevre dostu süreçlerle üretilmiştir.",
    images: ["/products/aura-1.jpg", "/products/aura-2.jpg"],
    inStock: true,
    featured: false,
  },
  {
    id: "9",
    slug: "celeste-kolye",
    name: "Celeste Kolye",
    description: "Gökyüzünün sonsuz mavisinden ilham alan Celeste, zarafeti boyun çizginize taşır.",
    story: "Celeste, Latince'de 'göksel' anlamına gelir. Bu kolye, gökyüzünün uçsuz bucaksız güzelliğini minimalist bir formda sunar.",
    price: 1100,
    category: "necklaces",
    materials: ["925 Ayar Gümüş", "Akuamarin Taş"],
    sustainability: "Etik kaynaklı taşlar ve geri dönüştürülmüş gümüş ile üretilmiştir.",
    images: ["/products/celeste-1.jpg", "/products/celeste-2.jpg"],
    inStock: true,
    featured: false,
  },
  {
    id: "10",
    slug: "sol-yuzuk",
    name: "Sol Yüzük",
    description: "Güneşin sıcaklığını parmağınızda hissedin. Sol, minimal formuyla dikkat çeker.",
    story: "Güneş, yaşamın kaynağıdır. Sol yüzük, bu sonsuz enerjiyi altın tonlarıyla parmağınıza taşır.",
    price: 980,
    category: "rings",
    materials: ["925 Ayar Gümüş", "18K Altın Kaplama"],
    sustainability: "Sürdürülebilir altın kaplama teknolojisi ile üretilmiştir.",
    images: ["/products/sol-1.jpg", "/products/sol-2.jpg"],
    inStock: true,
    featured: false,
  },
  {
    id: "11",
    slug: "vega-kupe",
    name: "Vega Küpe",
    description: "En parlak yıldızdan ilham alan Vega, kulaklarınızda zarafetin ışıltısını yaşatır.",
    story: "Vega, gökyüzünün en parlak yıldızlarından biridir. Bu küpe, o ışığın minimalist bir yorumudur.",
    price: 760,
    category: "earrings",
    materials: ["925 Ayar Gümüş", "18K Altın Kaplama"],
    sustainability: "Çevre dostu üretim süreçleri ile imal edilmiştir.",
    images: ["/products/vega-1.jpg", "/products/vega-2.jpg"],
    inStock: true,
    featured: false,
  },
  {
    id: "12",
    slug: "terra-bileklik",
    name: "Terra Bileklik",
    description: "Toprağın sağlamlığı ve zarafetini bir arada sunan Terra, günlük kullanım için idealdir.",
    story: "Terra, yeryüzünün gücünü ve güzelliğini bileğinize taşır. Dayanıklı yapısı ve zarif tasarımıyla her gün yanınızda.",
    price: 650,
    category: "bracelets",
    materials: ["925 Ayar Gümüş"],
    sustainability: "Geri dönüştürülmüş gümüş ve minimal ambalaj ile teslim edilir.",
    images: ["/products/terra-1.jpg", "/products/terra-2.jpg"],
    inStock: true,
    featured: false,
  },
];

export function getProductBySlug(slug: string): Product | undefined {
  return products.find((p) => p.slug === slug);
}

export function getProductsByCategory(category: string): Product[] {
  if (category === "all") return products;
  return products.filter((p) => p.category === category);
}

export function getFeaturedProducts(): Product[] {
  return products.filter((p) => p.featured);
}
